import daisyui from "daisyui";

/**
 * EzMatch ships six "notebook" themes instead of the stock daisyUI set.
 * Each one is a full daisyUI colour theme; `src/index.css` layers the matching
 * paper texture on top via the `[data-theme]` selector.
 */
const notebookThemes = {
  "grid-paper": {
    primary: "#3457d5",
    "primary-content": "#ffffff",
    secondary: "#e0567a",
    "secondary-content": "#ffffff",
    accent: "#e4572e",
    "accent-content": "#ffffff",
    neutral: "#2b3440",
    "neutral-content": "#f7f7f2",
    "base-100": "#fdfdf9",
    "base-200": "#f2f3ea",
    "base-300": "#e2e4d5",
    "base-content": "#26303a",
    info: "#3457d5",
    success: "#3aa76d",
    warning: "#e6a417",
    error: "#e4572e",
    "--rounded-box": "1.1rem",
    "--rounded-btn": "0.7rem",
  },
  blueprint: {
    primary: "#7dd3fc",
    "primary-content": "#08243d",
    secondary: "#a5b4fc",
    "secondary-content": "#08243d",
    accent: "#fbbf24",
    "accent-content": "#08243d",
    neutral: "#0a2540",
    "neutral-content": "#dbeafe",
    "base-100": "#0f3a63",
    "base-200": "#0c3357",
    "base-300": "#0a2b49",
    "base-content": "#e0efff",
    info: "#7dd3fc",
    success: "#6ee7b7",
    warning: "#fcd34d",
    error: "#fca5a5",
    "--rounded-box": "0.5rem",
    "--rounded-btn": "0.35rem",
  },
  parchment: {
    primary: "#8a5a2b",
    "primary-content": "#f9f1e0",
    secondary: "#9c6b3f",
    "secondary-content": "#f9f1e0",
    accent: "#a4262c",
    "accent-content": "#f9f1e0",
    neutral: "#3d2b1f",
    "neutral-content": "#f4e8d0",
    "base-100": "#f5e9d2",
    "base-200": "#eaddc0",
    "base-300": "#dcc8a4",
    "base-content": "#4b3621",
    info: "#4f6d7a",
    success: "#6b8f3a",
    warning: "#c98a2b",
    error: "#a4262c",
    "--rounded-box": "0.9rem",
    "--rounded-btn": "0.6rem",
  },
  chalkboard: {
    primary: "#f7f3e8",
    "primary-content": "#22312b",
    secondary: "#ffd9a0",
    "secondary-content": "#22312b",
    accent: "#a6e3a1",
    "accent-content": "#22312b",
    neutral: "#12100e",
    "neutral-content": "#eef2e9",
    "base-100": "#243430",
    "base-200": "#1d2b27",
    "base-300": "#16211d",
    "base-content": "#eef2e9",
    info: "#89dceb",
    success: "#a6e3a1",
    warning: "#f9e2af",
    error: "#f38ba8",
    "--rounded-box": "0.8rem",
    "--rounded-btn": "0.55rem",
  },
  watercolor: {
    primary: "#9a86d4",
    "primary-content": "#ffffff",
    secondary: "#6fc3c0",
    "secondary-content": "#ffffff",
    accent: "#f0a390",
    "accent-content": "#3b2f2a",
    neutral: "#4a4560",
    "neutral-content": "#f6f4fb",
    "base-100": "#fbfaf7",
    "base-200": "#f1edf8",
    "base-300": "#e2dcf0",
    "base-content": "#3b3a4a",
    info: "#8ec7e8",
    success: "#8fd3a8",
    warning: "#f2cd88",
    error: "#ef9a9a",
    "--rounded-box": "1.4rem",
    "--rounded-btn": "1rem",
  },
  manga: {
    primary: "#ff5d8f",
    "primary-content": "#ffffff",
    secondary: "#4cc2ff",
    "secondary-content": "#0b1020",
    accent: "#1c1c1e",
    "accent-content": "#ffffff",
    neutral: "#1c1c1e",
    "neutral-content": "#ffffff",
    "base-100": "#ffffff",
    "base-200": "#f2f2f4",
    "base-300": "#e0e0e6",
    "base-content": "#1c1c1e",
    info: "#4cc2ff",
    success: "#3ddc97",
    warning: "#ffc857",
    error: "#ff5d5d",
    "--rounded-box": "0.6rem",
    "--rounded-btn": "0.4rem",
  },
};

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Nunito"', "ui-sans-serif", "system-ui", "sans-serif"],
        hand: ['"Patrick Hand"', '"Comic Sans MS"', '"Segoe Print"', "cursive"],
        script: ['"Caveat"', '"Bradley Hand"', '"Segoe Script"', "cursive"],
      },
      boxShadow: {
        sketch: "3px 3px 0 0 rgba(0,0,0,0.18)",
        "sketch-lg": "6px 6px 0 0 rgba(0,0,0,0.18)",
      },
      rotate: { 1.5: "1.5deg", "-1.5": "-1.5deg" },
    },
  },
  plugins: [daisyui],
  daisyui: {
    themes: Object.entries(notebookThemes).map(([name, tokens]) => ({ [name]: tokens })),
  },
};
